// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mycalendar.proto

package pbcalendar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Event struct {
	Alerttime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=alerttime,proto3" json:"alerttime,omitempty"`
	Information          string               `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetAlerttime() *timestamp.Timestamp {
	if m != nil {
		return m.Alerttime
	}
	return nil
}

func (m *Event) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "pbcalendar.Result")
	proto.RegisterType((*Event)(nil), "pbcalendar.Event")
}

func init() { proto.RegisterFile("mycalendar.proto", fileDescriptor_9a09cb90c53a1eb3) }

var fileDescriptor_9a09cb90c53a1eb3 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3d, 0x8b, 0x83, 0x40,
	0x10, 0x86, 0xf1, 0xe0, 0xe4, 0x1c, 0x9b, 0xbb, 0x2d, 0x0e, 0xb1, 0x89, 0x58, 0xa5, 0x5a, 0x89,
	0x69, 0xd2, 0xa5, 0x08, 0x29, 0xd3, 0x48, 0xfe, 0xc0, 0xaa, 0xab, 0x08, 0xfb, 0x21, 0xbb, 0x63,
	0xc0, 0x7f, 0x1f, 0xb2, 0xab, 0x68, 0x39, 0xcf, 0xbc, 0x3c, 0xf3, 0x0e, 0xfc, 0xca, 0xb9, 0x61,
	0x82, 0xab, 0x96, 0x19, 0x3a, 0x1a, 0x8d, 0x9a, 0xc0, 0x58, 0xaf, 0x24, 0x3d, 0xf4, 0x5a, 0xf7,
	0x82, 0x17, 0x6e, 0x53, 0x4f, 0x5d, 0x81, 0x83, 0xe4, 0x16, 0x99, 0x1c, 0x7d, 0x38, 0xcf, 0x20,
	0xac, 0xb8, 0x9d, 0x04, 0x92, 0x7f, 0x08, 0x2d, 0x32, 0x9c, 0x6c, 0x12, 0x64, 0xc1, 0x31, 0xaa,
	0x96, 0x29, 0x6f, 0xe0, 0xfb, 0xfe, 0xe2, 0x0a, 0xc9, 0x05, 0x22, 0x26, 0xb8, 0xc1, 0x8f, 0xc2,
	0x65, 0xe2, 0x32, 0xa5, 0xde, 0x4f, 0x57, 0x3f, 0x7d, 0xae, 0xfe, 0x6a, 0x0b, 0x93, 0x0c, 0xe2,
	0x41, 0x75, 0xda, 0x48, 0x86, 0x83, 0x56, 0xc9, 0x97, 0xf3, 0xef, 0x51, 0x79, 0x05, 0x78, 0xcc,
	0xb7, 0xa5, 0x35, 0x39, 0xc1, 0x0f, 0x6b, 0x5b, 0x7f, 0xf5, 0x8f, 0x6e, 0xef, 0x50, 0x87, 0x52,
	0xb2, 0x47, 0xbe, 0x7d, 0x1d, 0xba, 0x06, 0xe7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xad,
	0x14, 0x23, 0x0f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyCalendarClient is the client API for MyCalendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyCalendarClient interface {
	AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Result, error)
}

type myCalendarClient struct {
	cc *grpc.ClientConn
}

func NewMyCalendarClient(cc *grpc.ClientConn) MyCalendarClient {
	return &myCalendarClient{cc}
}

func (c *myCalendarClient) AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/addEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyCalendarServer is the server API for MyCalendar service.
type MyCalendarServer interface {
	AddEvent(context.Context, *Event) (*Result, error)
}

// UnimplementedMyCalendarServer can be embedded to have forward compatible implementations.
type UnimplementedMyCalendarServer struct {
}

func (*UnimplementedMyCalendarServer) AddEvent(ctx context.Context, req *Event) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEvent not implemented")
}

func RegisterMyCalendarServer(s *grpc.Server, srv MyCalendarServer) {
	s.RegisterService(&_MyCalendar_serviceDesc, srv)
}

func _MyCalendar_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/AddEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).AddEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyCalendar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbcalendar.MyCalendar",
	HandlerType: (*MyCalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addEvent",
			Handler:    _MyCalendar_AddEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mycalendar.proto",
}
