version: "3.7"

services: 
    postgres:
      image: postgres:12.1-alpine
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Vfnhtirf79
        POSTGRES_DB: calendar
      ports:
        - "5432:5432"

    rabbitmq:
      image: rabbitmq:3.8.2
      container_name: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: calendar
        RABBITMQ_DEFAULT_PASS: Vfnhtirf79
      ports: 
        - "5672:5672"
