version: "3.7"
services: 
    db:
        image: postgres:9.6.16        
        container_name: postgres
        environment:
        networks:
          calendar_net:
            ipv4_address: 10.0.0.1
            aliases:
              - postgres
    
    rabbitmq:
        image: rabbitmq: 3.8.2
        container_name: rabbitmq
        environment:
        networks:
            calendar_net:
              ipv4_address: 10.0.0.1
              aliases:
                - rabbitmq
    
    mycalendar:
        image: 