version: "3.7"

services: 
    tests:
        image: gmax079/practice:tests
        container_name: tests
        environment:
          WAIT_HOSTS: localhost:8888 # for wait tool
        volumes:
          #- "~/etc:/etc/localtime:ro"
          - "/etc/localtime:/etc/localtime:ro"
        network_mode: "host"
