// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mycalendar.proto

package pbcalendar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEventRequest struct {
	Alerttime            *Date    `protobuf:"bytes,1,opt,name=alerttime,proto3" json:"alerttime,omitempty"`
	Information          string   `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{0}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetAlerttime() *Date {
	if m != nil {
		return m.Alerttime
	}
	return nil
}

func (m *CreateEventRequest) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

type CreateEventResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{1}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteEventRequest struct {
	Alerttime            *Date    `protobuf:"bytes,1,opt,name=alerttime,proto3" json:"alerttime,omitempty"`
	Information          string   `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventRequest) Reset()         { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()    {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{2}
}

func (m *DeleteEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequest.Unmarshal(m, b)
}
func (m *DeleteEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequest.Merge(m, src)
}
func (m *DeleteEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequest.Size(m)
}
func (m *DeleteEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequest proto.InternalMessageInfo

func (m *DeleteEventRequest) GetAlerttime() *Date {
	if m != nil {
		return m.Alerttime
	}
	return nil
}

func (m *DeleteEventRequest) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

type DeleteEventResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventResponse) Reset()         { *m = DeleteEventResponse{} }
func (m *DeleteEventResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEventResponse) ProtoMessage()    {}
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{3}
}

func (m *DeleteEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventResponse.Unmarshal(m, b)
}
func (m *DeleteEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventResponse.Merge(m, src)
}
func (m *DeleteEventResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEventResponse.Size(m)
}
func (m *DeleteEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventResponse proto.InternalMessageInfo

func (m *DeleteEventResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MoveEventRequest struct {
	Alerttime            *Date    `protobuf:"bytes,1,opt,name=alerttime,proto3" json:"alerttime,omitempty"`
	Information          string   `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	Newdate              *Date    `protobuf:"bytes,3,opt,name=newdate,proto3" json:"newdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveEventRequest) Reset()         { *m = MoveEventRequest{} }
func (m *MoveEventRequest) String() string { return proto.CompactTextString(m) }
func (*MoveEventRequest) ProtoMessage()    {}
func (*MoveEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{4}
}

func (m *MoveEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveEventRequest.Unmarshal(m, b)
}
func (m *MoveEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveEventRequest.Marshal(b, m, deterministic)
}
func (m *MoveEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveEventRequest.Merge(m, src)
}
func (m *MoveEventRequest) XXX_Size() int {
	return xxx_messageInfo_MoveEventRequest.Size(m)
}
func (m *MoveEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveEventRequest proto.InternalMessageInfo

func (m *MoveEventRequest) GetAlerttime() *Date {
	if m != nil {
		return m.Alerttime
	}
	return nil
}

func (m *MoveEventRequest) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

func (m *MoveEventRequest) GetNewdate() *Date {
	if m != nil {
		return m.Newdate
	}
	return nil
}

type MoveEventResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveEventResponse) Reset()         { *m = MoveEventResponse{} }
func (m *MoveEventResponse) String() string { return proto.CompactTextString(m) }
func (*MoveEventResponse) ProtoMessage()    {}
func (*MoveEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{5}
}

func (m *MoveEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveEventResponse.Unmarshal(m, b)
}
func (m *MoveEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveEventResponse.Marshal(b, m, deterministic)
}
func (m *MoveEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveEventResponse.Merge(m, src)
}
func (m *MoveEventResponse) XXX_Size() int {
	return xxx_messageInfo_MoveEventResponse.Size(m)
}
func (m *MoveEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveEventResponse proto.InternalMessageInfo

func (m *MoveEventResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Count struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Count) Reset()         { *m = Count{} }
func (m *Count) String() string { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()    {}
func (*Count) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{6}
}

func (m *Count) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Count.Unmarshal(m, b)
}
func (m *Count) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Count.Marshal(b, m, deterministic)
}
func (m *Count) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Count.Merge(m, src)
}
func (m *Count) XXX_Size() int {
	return xxx_messageInfo_Count.Size(m)
}
func (m *Count) XXX_DiscardUnknown() {
	xxx_messageInfo_Count.DiscardUnknown(m)
}

var xxx_messageInfo_Count proto.InternalMessageInfo

func (m *Count) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=Day,proto3" json:"Day,omitempty"`
	Hour                 int32    `protobuf:"varint,4,opt,name=Hour,proto3" json:"Hour,omitempty"`
	Minute               int32    `protobuf:"varint,5,opt,name=Minute,proto3" json:"Minute,omitempty"`
	Second               int32    `protobuf:"varint,6,opt,name=Second,proto3" json:"Second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{7}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Date) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *Date) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *Date) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

type EventsForDayRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=Day,proto3" json:"Day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsForDayRequest) Reset()         { *m = EventsForDayRequest{} }
func (m *EventsForDayRequest) String() string { return proto.CompactTextString(m) }
func (*EventsForDayRequest) ProtoMessage()    {}
func (*EventsForDayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{8}
}

func (m *EventsForDayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsForDayRequest.Unmarshal(m, b)
}
func (m *EventsForDayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsForDayRequest.Marshal(b, m, deterministic)
}
func (m *EventsForDayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsForDayRequest.Merge(m, src)
}
func (m *EventsForDayRequest) XXX_Size() int {
	return xxx_messageInfo_EventsForDayRequest.Size(m)
}
func (m *EventsForDayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsForDayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsForDayRequest proto.InternalMessageInfo

func (m *EventsForDayRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *EventsForDayRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *EventsForDayRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type EventsForWeekRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Week                 int32    `protobuf:"varint,2,opt,name=Week,proto3" json:"Week,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsForWeekRequest) Reset()         { *m = EventsForWeekRequest{} }
func (m *EventsForWeekRequest) String() string { return proto.CompactTextString(m) }
func (*EventsForWeekRequest) ProtoMessage()    {}
func (*EventsForWeekRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{9}
}

func (m *EventsForWeekRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsForWeekRequest.Unmarshal(m, b)
}
func (m *EventsForWeekRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsForWeekRequest.Marshal(b, m, deterministic)
}
func (m *EventsForWeekRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsForWeekRequest.Merge(m, src)
}
func (m *EventsForWeekRequest) XXX_Size() int {
	return xxx_messageInfo_EventsForWeekRequest.Size(m)
}
func (m *EventsForWeekRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsForWeekRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsForWeekRequest proto.InternalMessageInfo

func (m *EventsForWeekRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *EventsForWeekRequest) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

type EventsForMonthRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsForMonthRequest) Reset()         { *m = EventsForMonthRequest{} }
func (m *EventsForMonthRequest) String() string { return proto.CompactTextString(m) }
func (*EventsForMonthRequest) ProtoMessage()    {}
func (*EventsForMonthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a09cb90c53a1eb3, []int{10}
}

func (m *EventsForMonthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsForMonthRequest.Unmarshal(m, b)
}
func (m *EventsForMonthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsForMonthRequest.Marshal(b, m, deterministic)
}
func (m *EventsForMonthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsForMonthRequest.Merge(m, src)
}
func (m *EventsForMonthRequest) XXX_Size() int {
	return xxx_messageInfo_EventsForMonthRequest.Size(m)
}
func (m *EventsForMonthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsForMonthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsForMonthRequest proto.InternalMessageInfo

func (m *EventsForMonthRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *EventsForMonthRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateEventRequest)(nil), "pbcalendar.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "pbcalendar.CreateEventResponse")
	proto.RegisterType((*DeleteEventRequest)(nil), "pbcalendar.DeleteEventRequest")
	proto.RegisterType((*DeleteEventResponse)(nil), "pbcalendar.DeleteEventResponse")
	proto.RegisterType((*MoveEventRequest)(nil), "pbcalendar.MoveEventRequest")
	proto.RegisterType((*MoveEventResponse)(nil), "pbcalendar.MoveEventResponse")
	proto.RegisterType((*Count)(nil), "pbcalendar.Count")
	proto.RegisterType((*Date)(nil), "pbcalendar.Date")
	proto.RegisterType((*EventsForDayRequest)(nil), "pbcalendar.EventsForDayRequest")
	proto.RegisterType((*EventsForWeekRequest)(nil), "pbcalendar.EventsForWeekRequest")
	proto.RegisterType((*EventsForMonthRequest)(nil), "pbcalendar.EventsForMonthRequest")
}

func init() { proto.RegisterFile("mycalendar.proto", fileDescriptor_9a09cb90c53a1eb3) }

var fileDescriptor_9a09cb90c53a1eb3 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x49, 0x1c, 0x94, 0x09, 0xa0, 0x74, 0x5a, 0x90, 0x15, 0x51, 0x30, 0x3e, 0x55, 0x20,
	0x7c, 0x28, 0x77, 0x24, 0x88, 0xa9, 0x7a, 0x71, 0x25, 0xcc, 0x01, 0x71, 0xdc, 0xda, 0x53, 0x61,
	0x11, 0xef, 0x86, 0xf5, 0xba, 0xc8, 0x2f, 0xc0, 0x99, 0xc7, 0xe2, 0xb1, 0xd0, 0xae, 0xed, 0x7a,
	0x4d, 0x1d, 0x2a, 0x84, 0xe8, 0x6d, 0x7e, 0xbf, 0xf9, 0xbc, 0xdf, 0x8c, 0x61, 0x59, 0xd4, 0x29,
	0xdb, 0x10, 0xcf, 0x98, 0x0c, 0xb7, 0x52, 0x28, 0x81, 0xb0, 0x3d, 0xef, 0x22, 0xc1, 0x05, 0xe0,
	0x5a, 0x12, 0x53, 0xf4, 0xee, 0x92, 0xb8, 0x4a, 0xe8, 0x6b, 0x45, 0xa5, 0xc2, 0x10, 0xe6, 0x6c,
	0x43, 0x52, 0xa9, 0xbc, 0x20, 0xcf, 0xf1, 0x9d, 0xa3, 0xc5, 0xf1, 0x32, 0xec, 0xbb, 0xc2, 0x88,
	0x29, 0x4a, 0xfa, 0x12, 0xf4, 0x61, 0x91, 0xf3, 0x0b, 0x21, 0x0b, 0xa6, 0x72, 0xc1, 0xbd, 0x3b,
	0xbe, 0x73, 0x34, 0x4f, 0xec, 0x50, 0xf0, 0x12, 0xf6, 0x07, 0x73, 0xca, 0xad, 0xe0, 0x25, 0xe1,
	0x23, 0x98, 0x95, 0x8a, 0xa9, 0xaa, 0x34, 0x53, 0xe6, 0x49, 0xeb, 0x69, 0x5a, 0x11, 0x6d, 0xe8,
	0x36, 0x68, 0x0d, 0xe6, 0xdc, 0x40, 0xeb, 0x87, 0x03, 0xcb, 0x58, 0x5c, 0xfe, 0x67, 0x56, 0xf8,
	0x1c, 0xee, 0x72, 0xfa, 0x96, 0x31, 0x45, 0xde, 0x64, 0x07, 0x5e, 0x57, 0x10, 0xbc, 0x80, 0x3d,
	0x8b, 0xd1, 0x0d, 0xfc, 0x0f, 0xc1, 0x5d, 0x8b, 0x8a, 0x2b, 0x3c, 0x00, 0x37, 0xd5, 0x86, 0xc9,
	0xbb, 0x49, 0xe3, 0x04, 0xdf, 0x1d, 0x98, 0x6a, 0x74, 0x44, 0x98, 0x7e, 0x22, 0x26, 0xdb, 0xac,
	0xb1, 0x75, 0x4b, 0x2c, 0xb8, 0xfa, 0x6c, 0x08, 0xbb, 0x49, 0xe3, 0xe0, 0x12, 0x26, 0x11, 0xab,
	0x0d, 0x4d, 0x37, 0xd1, 0xa6, 0xee, 0x3d, 0x15, 0x95, 0xf4, 0xa6, 0x4d, 0xaf, 0xb6, 0x35, 0x9f,
	0x38, 0xe7, 0x95, 0x22, 0xcf, 0x35, 0xd1, 0xd6, 0xd3, 0xf1, 0x0f, 0x94, 0x0a, 0x9e, 0x79, 0xb3,
	0x26, 0xde, 0x78, 0xc1, 0x7b, 0xd8, 0x37, 0x1f, 0x54, 0x9e, 0x08, 0x19, 0xb1, 0xba, 0x7b, 0xe9,
	0x7f, 0xa0, 0x15, 0xbc, 0x86, 0x83, 0x2b, 0xc8, 0x8f, 0x44, 0x5f, 0xfe, 0x84, 0x89, 0x30, 0xd5,
	0x25, 0x2d, 0xa4, 0xb1, 0x83, 0x37, 0xf0, 0xf0, 0xaa, 0xdf, 0xcc, 0xf8, 0x6b, 0x52, 0xc7, 0x3f,
	0x27, 0x00, 0x71, 0xbd, 0x6e, 0x75, 0xc4, 0x33, 0x58, 0xa4, 0xfd, 0x49, 0xe0, 0x13, 0x5b, 0xe3,
	0xeb, 0x37, 0xb9, 0x7a, 0xba, 0x33, 0xdf, 0x8a, 0x7e, 0x06, 0x8b, 0xac, 0xdf, 0xe5, 0x21, 0xde,
	0xf5, 0x63, 0x1a, 0xe2, 0x8d, 0x1d, 0xc1, 0x29, 0xcc, 0x8b, 0x6e, 0xb3, 0xf0, 0xb1, 0x5d, 0xfd,
	0xfb, 0x09, 0xac, 0x0e, 0x77, 0x64, 0x5b, 0xa4, 0xb7, 0x70, 0x8f, 0x2c, 0x39, 0x71, 0x30, 0x7a,
	0x44, 0xe8, 0xd5, 0xde, 0xe0, 0x5b, 0xcd, 0xc6, 0x9e, 0xc0, 0x03, 0x1a, 0xbc, 0x3f, 0x3e, 0x1b,
	0x45, 0xb1, 0xb5, 0x19, 0xc3, 0x89, 0xe0, 0x3e, 0xd9, 0x7b, 0x80, 0xfe, 0x28, 0x8c, 0xb5, 0x22,
	0x23, 0x28, 0xe7, 0x33, 0xf3, 0x27, 0x7d, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xde, 0x04, 0x26,
	0x32, 0x5d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyCalendarClient is the client API for MyCalendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyCalendarClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	MoveEvent(ctx context.Context, in *MoveEventRequest, opts ...grpc.CallOption) (*MoveEventResponse, error)
	EventsForDay(ctx context.Context, in *EventsForDayRequest, opts ...grpc.CallOption) (*Count, error)
	EventsForMonth(ctx context.Context, in *EventsForMonthRequest, opts ...grpc.CallOption) (*Count, error)
	EventsForWeek(ctx context.Context, in *EventsForWeekRequest, opts ...grpc.CallOption) (*Count, error)
}

type myCalendarClient struct {
	cc *grpc.ClientConn
}

func NewMyCalendarClient(cc *grpc.ClientConn) MyCalendarClient {
	return &myCalendarClient{cc}
}

func (c *myCalendarClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/createEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myCalendarClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/deleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myCalendarClient) MoveEvent(ctx context.Context, in *MoveEventRequest, opts ...grpc.CallOption) (*MoveEventResponse, error) {
	out := new(MoveEventResponse)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/moveEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myCalendarClient) EventsForDay(ctx context.Context, in *EventsForDayRequest, opts ...grpc.CallOption) (*Count, error) {
	out := new(Count)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/eventsForDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myCalendarClient) EventsForMonth(ctx context.Context, in *EventsForMonthRequest, opts ...grpc.CallOption) (*Count, error) {
	out := new(Count)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/eventsForMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myCalendarClient) EventsForWeek(ctx context.Context, in *EventsForWeekRequest, opts ...grpc.CallOption) (*Count, error) {
	out := new(Count)
	err := c.cc.Invoke(ctx, "/pbcalendar.MyCalendar/eventsForWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyCalendarServer is the server API for MyCalendar service.
type MyCalendarServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	MoveEvent(context.Context, *MoveEventRequest) (*MoveEventResponse, error)
	EventsForDay(context.Context, *EventsForDayRequest) (*Count, error)
	EventsForMonth(context.Context, *EventsForMonthRequest) (*Count, error)
	EventsForWeek(context.Context, *EventsForWeekRequest) (*Count, error)
}

// UnimplementedMyCalendarServer can be embedded to have forward compatible implementations.
type UnimplementedMyCalendarServer struct {
}

func (*UnimplementedMyCalendarServer) CreateEvent(ctx context.Context, req *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedMyCalendarServer) DeleteEvent(ctx context.Context, req *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedMyCalendarServer) MoveEvent(ctx context.Context, req *MoveEventRequest) (*MoveEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveEvent not implemented")
}
func (*UnimplementedMyCalendarServer) EventsForDay(ctx context.Context, req *EventsForDayRequest) (*Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsForDay not implemented")
}
func (*UnimplementedMyCalendarServer) EventsForMonth(ctx context.Context, req *EventsForMonthRequest) (*Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsForMonth not implemented")
}
func (*UnimplementedMyCalendarServer) EventsForWeek(ctx context.Context, req *EventsForWeekRequest) (*Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventsForWeek not implemented")
}

func RegisterMyCalendarServer(s *grpc.Server, srv MyCalendarServer) {
	s.RegisterService(&_MyCalendar_serviceDesc, srv)
}

func _MyCalendar_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyCalendar_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyCalendar_MoveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).MoveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/MoveEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).MoveEvent(ctx, req.(*MoveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyCalendar_EventsForDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsForDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).EventsForDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/EventsForDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).EventsForDay(ctx, req.(*EventsForDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyCalendar_EventsForMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsForMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).EventsForMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/EventsForMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).EventsForMonth(ctx, req.(*EventsForMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyCalendar_EventsForWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsForWeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyCalendarServer).EventsForWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbcalendar.MyCalendar/EventsForWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyCalendarServer).EventsForWeek(ctx, req.(*EventsForWeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyCalendar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbcalendar.MyCalendar",
	HandlerType: (*MyCalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createEvent",
			Handler:    _MyCalendar_CreateEvent_Handler,
		},
		{
			MethodName: "deleteEvent",
			Handler:    _MyCalendar_DeleteEvent_Handler,
		},
		{
			MethodName: "moveEvent",
			Handler:    _MyCalendar_MoveEvent_Handler,
		},
		{
			MethodName: "eventsForDay",
			Handler:    _MyCalendar_EventsForDay_Handler,
		},
		{
			MethodName: "eventsForMonth",
			Handler:    _MyCalendar_EventsForMonth_Handler,
		},
		{
			MethodName: "eventsForWeek",
			Handler:    _MyCalendar_EventsForWeek_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mycalendar.proto",
}
