scrape_configs:
    - job_name: 'postgres_exporter'
      scrape_interval: 5s
      static_configs:
      - targets: ['pgexporter:9187']

    - job_name: 'sender'
      scrape_interval: 5s
      static_configs:
      - targets: ['host.docker.internal:9102']
