scrape_configs:
    - job_name: 'postgres'
      scrape_interval: 5s
      static_configs:
      - targets: ['pgexporter:9187']
        labels: 
          groups: 'calendar'

    - job_name: 'sender'
      scrape_interval: 5s
      static_configs:
      - targets: ['host.docker.internal:9189']

    - job_name: 'mycalendar http api'
      scrape_interval: 5s
      static_configs:
        - targets: ['host.docker.internal:9188']

rule_files:
  - 'prometheus.rules.yml'
