scrape_configs:
    - job_name: 'postgres'
      scrape_interval: 5s
      static_configs:
      - targets: ['pgexporter:9187']

    - job_name: 'sender'
      scrape_interval: 5s
      static_configs:
      - targets: ['sender:9189']

    - job_name: 'mycalendar http api'
      scrape_interval: 5s
      static_configs:
        - targets: ['mycalendar:9188']
